const $=s=>document.querySelector(s);
const statusEl=$('#status');
let history=[];
function addMsg(role,text){const box=$('#messages');const row=document.createElement('div');row.className='msg '+role;const b=document.createElement('div');b.className='bubble';b.textContent=text;row.appendChild(b);box.appendChild(row);box.scrollTop=box.scrollHeight;return b}
function speak(text){if(!('speechSynthesis' in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=1;u.lang=/[\u0980-\u09FF]/.test(text)?'as-IN':'en-IN';speechSynthesis.speak(u)}
async function send(){const input=$('#prompt');const message=input.value.trim();if(!message)return;input.value='';addMsg('user',message);const wait=addMsg('assistant','Thinking…');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');wait.textContent=d.answer;history.push({role:'user',content:message},{role:'assistant',content:d.answer});history=history.slice(-12);$('#speak').onclick=()=>speak(d.answer)}catch(e){wait.textContent='Error: '+e.message}}
$('#send')?.addEventListener('click',send);$('#prompt')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#speak')?.addEventListener('click',()=>{const last=[...document.querySelectorAll('.assistant .bubble')].pop();if(last)speak(last.textContent)});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='en-IN';rec.interimResults=false;rec.continuous=false;rec.onstart=()=>$('#mic').textContent='⏺';rec.onend=()=>$('#mic').textContent='🎙';rec.onresult=e=>{$('#prompt').value=e.results[0][0].transcript;send()};$('#mic').addEventListener('click',()=>rec.start())}else{$('#mic').disabled=true;$('#mic').title='Voice input is not supported in this browser.'}
fetch('/api/status').then(r=>r.json()).then(x=>{statusEl.textContent=x.configured?'● AI ONLINE':'● API KEY NEEDED';statusEl.style.color=x.configured?'#6ef2c1':'#ffcc66'}).catch(()=>statusEl.textContent='● OFFLINE');
